version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: secure-ai-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/vectorstore:/app/vectorstore

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: secure-ai-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend